{{- if .Values.mariadb.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "apache-guacamole.mariadb.fullname" . }}
  labels:
    {{- include "apache-guacamole.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "apache-guacamole.selectorLabels" . | nindent 6 }}
      component: mariadb
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
{{- end }}
