{{- if .Values.guacamole.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "apache-guacamole.guacamole.fullname" . }}
  labels:
    {{- include "apache-guacamole.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "apache-guacamole.selectorLabels" . | nindent 6 }}
      component: guacamole
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - ports:
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 22
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "apache-guacamole.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          component: guacd
    ports:
    - protocol: TCP
      port: {{ .Values.guacd.service.port }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "apache-guacamole.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          component: mariadb
    ports:
    - protocol: TCP
      port: {{ .Values.mariadb.service.port }}
{{- end }}
